#!/usr/bin/env python3
"""Generate THIRD-PARTY-NOTICES.md and license files from the CLI's NuGet lock file.

Run after `dotnet restore` so every locked package is in the NuGet global packages folder.
With --check, report whether the committed notices are current instead of writing them.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import xml.etree.ElementTree as ElementTree
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LOCK_FILE = ROOT / "src/Replicera.Cli/packages.lock.json"
NOTICES_FILE = ROOT / "THIRD-PARTY-NOTICES.md"
LICENSE_DIRECTORY = ROOT / "third-party-licenses"

# Packages that publish only a license URL. Each entry names the license for the notices table.
LICENSE_URL_NAMES = {
    "Microsoft.PowerPlatform.Dataverse.Client": "Microsoft Power Apps and Dynamics 365 SDK license",
}

# Additional terms that apply beyond the license shown in the table.
PACKAGE_NOTES = {
    "Microsoft.PowerPlatform.Dataverse.Client": (
        "Its distributable DLLs are subject to the distribution requirements in that license."
    ),
    "Oracle.ManagedDataAccess.Core": "Its package license is the Oracle Free Use Terms and Conditions.",
}

HEADER = """# Third-Party Notices

Replicera Community source code is licensed under MPL-2.0. Third-party packages retain their own licenses; the project license does not replace those terms.

This file is generated by `scripts/generate_third_party_notices.py` from `src/Replicera.Cli/packages.lock.json`. Do not edit it by hand; rerun the script after changing package versions.

## Packages distributed with Replicera

The license texts referenced below are in the `third-party-licenses` directory, which release packages include. Packages under the MIT license carry the copyright notice listed for them together with the MIT license text.

| Package | Version | License | Copyright |
| --- | --- | --- | --- |
"""

FOOTER = """
## .NET runtime

Self-contained release packages include the .NET runtime. Its license and third-party notices are included in those packages as `third-party-licenses/dotnet-runtime-LICENSE.txt` and `third-party-licenses/dotnet-runtime-THIRD-PARTY-NOTICES.txt`. Framework-dependent builds use the separately installed .NET runtime.

## Test dependencies

Test projects use xUnit and related packages under Apache-2.0 and Microsoft test and coverage packages under MIT. They are not distributed with Replicera. Their exact versions are recorded in each test project's `packages.lock.json`.
"""


@dataclass(frozen=True)
class Package:
    id: str
    version: str
    license_type: str | None
    license_value: str | None
    license_url: str | None
    copyright: str | None


def global_packages_folder() -> Path:
    configured = os.environ.get("NUGET_PACKAGES")
    if configured:
        return Path(configured)
    output = subprocess.run(
        ["dotnet", "nuget", "locals", "global-packages", "--list"],
        check=True,
        capture_output=True,
        text=True,
    ).stdout
    match = re.search(r"global-packages:\s*(.+)", output)
    if match is None:
        raise SystemExit("Could not determine the NuGet global packages folder.")
    return Path(match.group(1).strip())


def locked_packages() -> dict[str, str]:
    lock = json.loads(LOCK_FILE.read_text(encoding="utf-8"))
    packages: dict[str, str] = {}
    for dependencies in lock["dependencies"].values():
        for name, dependency in dependencies.items():
            if dependency["type"] != "Project":
                packages[name] = dependency["resolved"]
    return packages


def read_package(folder: Path, package_id: str, version: str) -> tuple[Package, Path]:
    directory = folder / package_id.lower() / version.lower()
    nuspec = directory / f"{package_id.lower()}.nuspec"
    if not nuspec.exists():
        raise SystemExit(f"{nuspec} was not found; run 'dotnet restore Replicera.sln' first.")
    metadata = ElementTree.parse(nuspec).getroot()

    def element(name: str) -> ElementTree.Element | None:
        return next((item for item in metadata.iter() if item.tag.split("}")[-1] == name), None)

    def text(name: str) -> str | None:
        found = element(name)
        return found.text.strip() if found is not None and found.text else None

    license_element = element("license")
    return (
        Package(
            id=text("id") or package_id,
            version=version,
            license_type=license_element.get("type") if license_element is not None else None,
            license_value=text("license"),
            license_url=text("licenseUrl"),
            copyright=text("copyright"),
        ),
        directory,
    )


def expression_licenses(expression: str) -> list[str]:
    return [token for token in re.split(r"[\s()]+", expression) if token and token not in ("AND", "OR", "WITH")]


def build(folder: Path) -> tuple[str, dict[Path, bytes]]:
    rows: list[str] = []
    notes: list[str] = []
    files: dict[Path, bytes] = {}
    missing_texts: set[str] = set()
    for package_id, version in sorted(locked_packages().items(), key=lambda item: item[0].lower()):
        package, directory = read_package(folder, package_id, version)
        if package.license_type == "expression" and package.license_value:
            licenses = expression_licenses(package.license_value)
            for name in licenses:
                if not (LICENSE_DIRECTORY / f"{name}.txt").exists():
                    missing_texts.add(name)
            license_cell = package.license_value
            for name in licenses:
                license_cell = license_cell.replace(name, f"[{name}](third-party-licenses/{name}.txt)")
        elif package.license_type == "file" and package.license_value:
            target = LICENSE_DIRECTORY / f"{package.id}-LICENSE.txt"
            files[target] = (directory / package.license_value).read_bytes()
            license_cell = f"[Package license](third-party-licenses/{target.name})"
        elif package.license_url:
            name = LICENSE_URL_NAMES.get(package.id, "License")
            license_cell = f"[{name}]({package.license_url})"
        else:
            raise SystemExit(f"{package.id} {version} does not declare a license; add it to this script.")
        rows.append(
            f"| `{package.id}` | {package.version} | {license_cell} | {escape(package.copyright or '')} |"
        )
        if package.id in PACKAGE_NOTES:
            notes.append(f"- `{package.id}`: {PACKAGE_NOTES[package.id]}")

    if missing_texts:
        raise SystemExit(
            "Add license texts to third-party-licenses for: " + ", ".join(sorted(missing_texts))
        )

    content = HEADER + "\n".join(rows) + "\n"
    if notes:
        content += "\nAdditional terms:\n\n" + "\n".join(notes) + "\n"
    return content + FOOTER, files


def escape(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if the committed notices are out of date")
    args = parser.parse_args()

    content, files = build(global_packages_folder())
    expected = {NOTICES_FILE: content.encode("utf-8"), **files}
    if args.check:
        stale = [path for path, data in expected.items() if not path.exists() or path.read_bytes() != data]
        if stale:
            for path in stale:
                print(f"Out of date: {path.relative_to(ROOT)}", file=sys.stderr)
            print("Run scripts/generate_third_party_notices.py and commit the result.", file=sys.stderr)
            sys.exit(1)
        print("Third-party notices are up to date.")
        return

    LICENSE_DIRECTORY.mkdir(exist_ok=True)
    for path, data in expected.items():
        path.write_bytes(data)
    print(f"Wrote {NOTICES_FILE.relative_to(ROOT)} and {len(files)} package license files.")


if __name__ == "__main__":
    main()
